export const products = [
    {
        "name": 'iPhone 11',
        "image": '/assets/"image"s (32).jpeg',
        "time": '1 h 14m',
        "age": '+16',
        "year": '1999',
        "desc": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Praesentium hic rem eveniet error possimus, neque ex doloribus.',
        "genre": 'Action',
    },
    {
        "name": 'iPhone 11',
        "image": '/assets/"image"s (31).jpeg',
        "time": '1 h 14m',
        "age": '+16',
        "year": '1999',
        "desc": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Praesentium hic rem eveniet error possimus, neque ex doloribus.',
        "genre": 'Action',
    },
    {
        "name": 'iPhone 11',
        "image": '/assets/"image"s (21).jpeg',
        "time": '1 h 14m',
        "age": '+16',
        "year": '1999',
        "desc": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Praesentium hic rem eveniet error possimus, neque ex doloribus.',
        "genre": 'Action',
    },
    {
        "name": 'iPhone 11',
        "image": '/assets/"image"s (16).jpeg',
        "time": '1 h 14m',
        "age": '+16',
        "year": '1999',
        "desc": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Praesentium hic rem eveniet error possimus, neque ex doloribus.',
        "genre": 'Action',
    },
    {
        "name": 'iPhone 11',
        "image": '/assets/top.jpg',
        "time": '1 h 14m',
        "age": '+16',
        "year": '1999',
        "desc": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Praesentium hic rem eveniet error possimus, neque ex doloribus.',
        "genre": 'Action',
    },
    {
        "name": 'iPhone 11',
        "image": '/assets/imp.png',
        "time": '1 h 14m',
        "age": '+16',
        "year": '1999',
        "desc": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Praesentium hic rem eveniet error possimus, neque ex doloribus.',
        "genre": 'Action',
    },
    {
        "name": 'iPhone 11',
        "image": '/assets/"image"s (19).jpeg',
        "time": '1 h 14m',
        "age": '+16',
        "year": '1999',
        "desc": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Praesentium hic rem eveniet error possimus, neque ex doloribus.',
        "genre": 'Action',
    },
    {
        "name": 'iPhone 11',
        "image": '/assets/"image"s (20).jpeg',
        "time": '1 h 14m',
        "age": '+16',
        "year": '1999',
        "desc": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Praesentium hic rem eveniet error possimus, neque ex doloribus.',
        "genre": 'Action',
    },
    {
        "name": 'iPhone 11',
        "image": '/assets/"image"s (22).jpeg',
        "time": '1 h 14m',
        "age": '+16',
        "year": '1999',
        "desc": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Praesentium hic rem eveniet error possimus, neque ex doloribus.',
        "genre": 'Action',
    },
    {
        "name": 'iPhone 11',
        "image": '/assets/"image"s (27).jpeg',
        "time": '1 h 14m',
        "age": '+16',
        "year": '1999',
        "desc": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Praesentium hic rem eveniet error possimus, neque ex doloribus.',
        "genre": 'Action',
    },
    {
        "name": 'iPhone 11',
        "image": '/assets/"image"s (30).jpeg',
        "time": '1 h 14m',
        "age": '+16',
        "year": '1999',
        "desc": 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Praesentium hic rem eveniet error possimus, neque ex doloribus.',
        "genre": 'Action',
    }
]